# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /media/ws-ml/Data-ml1/UnrealEngine
GAMEPROJECTFILE =/mnt/09e53a81-41fc-46df-ab07-85b73e480158/ws-ml/GitHub/UnrealProjects/side-runner/SideRunner.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	SideRunner-Linux-DebugGame  \
	SideRunner-Linux-Shipping  \
	SideRunner \
	SideRunnerEditor-Linux-DebugGame  \
	SideRunnerEditor-Linux-Shipping  \
	SideRunnerEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/RunMono.sh" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool.exe"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend UnrealEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UnrealEditor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

SideRunner-Linux-DebugGame:
	 $(PROJECTBUILD) SideRunner Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SideRunner-Linux-Shipping:
	 $(PROJECTBUILD) SideRunner Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SideRunner:
	 $(PROJECTBUILD) SideRunner Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

SideRunnerEditor-Linux-DebugGame:
	 $(PROJECTBUILD) SideRunnerEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SideRunnerEditor-Linux-Shipping:
	 $(PROJECTBUILD) SideRunnerEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SideRunnerEditor:
	 $(PROJECTBUILD) SideRunnerEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
